In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\A\Downloads\COVID.csv")
df

,Outcome,Week End,Age Group,Unvaccinated Rate,Vaccinated Rate,Boosted Rate,Crude Vaccinated Ratio,Crude Boosted Ratio,Age-Adjusted Unvaccinated Rate,Age-Adjusted Vaccinated Rate,...,Age-Adjusted Vaccinated Ratio,Age-Adjusted Boosted Ratio,Population Unvaccinated,Population Vaccinated,Population Boosted,Outcome Unvaccinated,Outcome Vaccinated,Outcome Boosted,Age Group Min,Age Group Max
0,Deaths,10/01/2022,All,0.3,0.1,0.9,3.0,0.3,0.4,0.3,...,1.3,0.7,591822,842535.0,1037067.0,2,1.0,9.0,999,999
1,Deaths,07/09/2022,0-4,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,0,NaN,NaN,0,4
2,Cases,11/12/2022,0-4,82.4,5.5,NaN,15.0,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,134,9.0,NaN,0,4
3,Hospitalizations,08/13/2022,0-4,7.4,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,12,0.0,NaN,0,4
4,Cases,02/26/2022,0-4,54.1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,88,NaN,NaN,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Deaths,11/13/2021,65-79,8.7,5.5,1.8,1.6,4.8,NaN,NaN,...,NaN,NaN,57295,146087.0,56482.0,5,8.0,1.0,65,79
3749,Cases,09/30/2023,18-29,51.0,17.7,19.8,2.9,2.6,NaN,NaN,...,NaN,NaN,72503,214130.0,161728.0,37,38.0,32.0,18,29
3750,Deaths,10/09/2021,80+,16.4,3.8,NaN,4.3,NaN,NaN,NaN,...,NaN,NaN,30481,52266.0,NaN,5,2.0,NaN,80,200
3751,Deaths,09/25/2021,80+,19.4,1.9,NaN,10.2,NaN,NaN,NaN,...,NaN,NaN,30936,52848.0,NaN,6,1.0,NaN,80,200
3752,Cases,10/16/2021,80+,33.0,40.0,NaN,0.8,NaN,NaN,NaN,...,NaN,NaN,30320,49996.0,NaN,10,20.0,NaN,80,200

In [3]:
df.isnull().sum()

Outcome                              0
Week End                             0
Age Group                            0
Unvaccinated Rate                    0
Vaccinated Rate                    327
Boosted Rate                      1224
Crude Vaccinated Ratio            1433
Crude Boosted Ratio               1992
Age-Adjusted Unvaccinated Rate    3336
Age-Adjusted Vaccinated Rate      3336
Age-Adjusted Boosted Rate         3423
Age-Adjusted Vaccinated Ratio     3373
Age-Adjusted Boosted Ratio        3441
Population Unvaccinated              0
Population Vaccinated              540
Population Boosted                1224
Outcome Unvaccinated                 0
Outcome Vaccinated                 327
Outcome Boosted                   1224
Age Group Min                        0
Age Group Max                        0
dtype: int64

In [13]:
vacc_mean = df["Vaccinated Rate"].mean()
df["Vaccinated Rate"] = df["Vaccinated Rate"].fillna(vacc_mean)
df

,Outcome,Week End,Age Group,Unvaccinated Rate,Vaccinated Rate,Boosted Rate,Crude Vaccinated Ratio,Crude Boosted Ratio,Age-Adjusted Unvaccinated Rate,Age-Adjusted Vaccinated Rate,...,Age-Adjusted Vaccinated Ratio,Age-Adjusted Boosted Ratio,Population Unvaccinated,Population Vaccinated,Population Boosted,Outcome Unvaccinated,Outcome Vaccinated,Outcome Boosted,Age Group Min,Age Group Max
0,Deaths,10/01/2022,All,0.3,0.100000,0.9,3.0,0.3,0.4,0.3,...,1.3,0.7,591822,842535.0,1037067.0,2,1.0,9.0,999,999
1,Deaths,07/09/2022,0-4,0.0,42.439521,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,0,NaN,NaN,0,4
2,Cases,11/12/2022,0-4,82.4,5.500000,NaN,15.0,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,134,9.0,NaN,0,4
3,Hospitalizations,08/13/2022,0-4,7.4,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,12,0.0,NaN,0,4
4,Cases,02/26/2022,0-4,54.1,42.439521,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,88,NaN,NaN,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Deaths,11/13/2021,65-79,8.7,5.500000,1.8,1.6,4.8,NaN,NaN,...,NaN,NaN,57295,146087.0,56482.0,5,8.0,1.0,65,79
3749,Cases,09/30/2023,18-29,51.0,17.700000,19.8,2.9,2.6,NaN,NaN,...,NaN,NaN,72503,214130.0,161728.0,37,38.0,32.0,18,29
3750,Deaths,10/09/2021,80+,16.4,3.800000,NaN,4.3,NaN,NaN,NaN,...,NaN,NaN,30481,52266.0,NaN,5,2.0,NaN,80,200
3751,Deaths,09/25/2021,80+,19.4,1.900000,NaN,10.2,NaN,NaN,NaN,...,NaN,NaN,30936,52848.0,NaN,6,1.0,NaN,80,200
3752,Cases,10/16/2021,80+,33.0,40.000000,NaN,0.8,NaN,NaN,NaN,...,NaN,NaN,30320,49996.0,NaN,10,20.0,NaN,80,200

In [15]:
Boost_mean = df["Boosted Rate"].mean()
df["Boosted Rate"] = df["Boosted Rate"].fillna(Boost_mean)
df

,Outcome,Week End,Age Group,Unvaccinated Rate,Vaccinated Rate,Boosted Rate,Crude Vaccinated Ratio,Crude Boosted Ratio,Age-Adjusted Unvaccinated Rate,Age-Adjusted Vaccinated Rate,...,Age-Adjusted Vaccinated Ratio,Age-Adjusted Boosted Ratio,Population Unvaccinated,Population Vaccinated,Population Boosted,Outcome Unvaccinated,Outcome Vaccinated,Outcome Boosted,Age Group Min,Age Group Max
0,Deaths,10/01/2022,All,0.3,0.100000,0.900000,3.0,0.3,0.4,0.3,...,1.3,0.7,591822,842535.0,1037067.0,2,1.0,9.0,999,999
1,Deaths,07/09/2022,0-4,0.0,42.439521,48.649783,NaN,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,0,NaN,NaN,0,4
2,Cases,11/12/2022,0-4,82.4,5.500000,48.649783,15.0,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,134,9.0,NaN,0,4
3,Hospitalizations,08/13/2022,0-4,7.4,0.000000,48.649783,NaN,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,12,0.0,NaN,0,4
4,Cases,02/26/2022,0-4,54.1,42.439521,48.649783,NaN,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,88,NaN,NaN,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Deaths,11/13/2021,65-79,8.7,5.500000,1.800000,1.6,4.8,NaN,NaN,...,NaN,NaN,57295,146087.0,56482.0,5,8.0,1.0,65,79
3749,Cases,09/30/2023,18-29,51.0,17.700000,19.800000,2.9,2.6,NaN,NaN,...,NaN,NaN,72503,214130.0,161728.0,37,38.0,32.0,18,29
3750,Deaths,10/09/2021,80+,16.4,3.800000,48.649783,4.3,NaN,NaN,NaN,...,NaN,NaN,30481,52266.0,NaN,5,2.0,NaN,80,200
3751,Deaths,09/25/2021,80+,19.4,1.900000,48.649783,10.2,NaN,NaN,NaN,...,NaN,NaN,30936,52848.0,NaN,6,1.0,NaN,80,200
3752,Cases,10/16/2021,80+,33.0,40.000000,48.649783,0.8,NaN,NaN,NaN,...,NaN,NaN,30320,49996.0,NaN,10,20.0,NaN,80,200

In [17]:
Crude_vacc_mean = df["Crude Vaccinated Ratio"].mean()
df["Crude Vaccinated Ratio"] = df["Crude Vaccinated Ratio"].fillna(Crude_vacc_mean)
df

,Outcome,Week End,Age Group,Unvaccinated Rate,Vaccinated Rate,Boosted Rate,Crude Vaccinated Ratio,Crude Boosted Ratio,Age-Adjusted Unvaccinated Rate,Age-Adjusted Vaccinated Rate,...,Age-Adjusted Vaccinated Ratio,Age-Adjusted Boosted Ratio,Population Unvaccinated,Population Vaccinated,Population Boosted,Outcome Unvaccinated,Outcome Vaccinated,Outcome Boosted,Age Group Min,Age Group Max
0,Deaths,10/01/2022,All,0.3,0.100000,0.900000,3.00000,0.3,0.4,0.3,...,1.3,0.7,591822,842535.0,1037067.0,2,1.0,9.0,999,999
1,Deaths,07/09/2022,0-4,0.0,42.439521,48.649783,4.54694,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,0,NaN,NaN,0,4
2,Cases,11/12/2022,0-4,82.4,5.500000,48.649783,15.00000,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,134,9.0,NaN,0,4
3,Hospitalizations,08/13/2022,0-4,7.4,0.000000,48.649783,4.54694,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,12,0.0,NaN,0,4
4,Cases,02/26/2022,0-4,54.1,42.439521,48.649783,4.54694,NaN,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,88,NaN,NaN,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Deaths,11/13/2021,65-79,8.7,5.500000,1.800000,1.60000,4.8,NaN,NaN,...,NaN,NaN,57295,146087.0,56482.0,5,8.0,1.0,65,79
3749,Cases,09/30/2023,18-29,51.0,17.700000,19.800000,2.90000,2.6,NaN,NaN,...,NaN,NaN,72503,214130.0,161728.0,37,38.0,32.0,18,29
3750,Deaths,10/09/2021,80+,16.4,3.800000,48.649783,4.30000,NaN,NaN,NaN,...,NaN,NaN,30481,52266.0,NaN,5,2.0,NaN,80,200
3751,Deaths,09/25/2021,80+,19.4,1.900000,48.649783,10.20000,NaN,NaN,NaN,...,NaN,NaN,30936,52848.0,NaN,6,1.0,NaN,80,200
3752,Cases,10/16/2021,80+,33.0,40.000000,48.649783,0.80000,NaN,NaN,NaN,...,NaN,NaN,30320,49996.0,NaN,10,20.0,NaN,80,200

In [18]:
Crude_Boost_mean = df["Crude Boosted Ratio"].mean()
df["Crude Boosted Ratio"] = df["Crude Boosted Ratio"].fillna(Crude_Boost_mean)
df

,Outcome,Week End,Age Group,Unvaccinated Rate,Vaccinated Rate,Boosted Rate,Crude Vaccinated Ratio,Crude Boosted Ratio,Age-Adjusted Unvaccinated Rate,Age-Adjusted Vaccinated Rate,...,Age-Adjusted Vaccinated Ratio,Age-Adjusted Boosted Ratio,Population Unvaccinated,Population Vaccinated,Population Boosted,Outcome Unvaccinated,Outcome Vaccinated,Outcome Boosted,Age Group Min,Age Group Max
0,Deaths,10/01/2022,All,0.3,0.100000,0.900000,3.00000,0.3000,0.4,0.3,...,1.3,0.7,591822,842535.0,1037067.0,2,1.0,9.0,999,999
1,Deaths,07/09/2022,0-4,0.0,42.439521,48.649783,4.54694,2.9523,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,0,NaN,NaN,0,4
2,Cases,11/12/2022,0-4,82.4,5.500000,48.649783,15.00000,2.9523,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,134,9.0,NaN,0,4
3,Hospitalizations,08/13/2022,0-4,7.4,0.000000,48.649783,4.54694,2.9523,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,12,0.0,NaN,0,4
4,Cases,02/26/2022,0-4,54.1,42.439521,48.649783,4.54694,2.9523,NaN,NaN,...,NaN,NaN,162642,NaN,NaN,88,NaN,NaN,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Deaths,11/13/2021,65-79,8.7,5.500000,1.800000,1.60000,4.8000,NaN,NaN,...,NaN,NaN,57295,146087.0,56482.0,5,8.0,1.0,65,79
3749,Cases,09/30/2023,18-29,51.0,17.700000,19.800000,2.90000,2.6000,NaN,NaN,...,NaN,NaN,72503,214130.0,161728.0,37,38.0,32.0,18,29
3750,Deaths,10/09/2021,80+,16.4,3.800000,48.649783,4.30000,2.9523,NaN,NaN,...,NaN,NaN,30481,52266.0,NaN,5,2.0,NaN,80,200
3751,Deaths,09/25/2021,80+,19.4,1.900000,48.649783,10.20000,2.9523,NaN,NaN,...,NaN,NaN,30936,52848.0,NaN,6,1.0,NaN,80,200
3752,Cases,10/16/2021,80+,33.0,40.000000,48.649783,0.80000,2.9523,NaN,NaN,...,NaN,NaN,30320,49996.0,NaN,10,20.0,NaN,80,200

In [19]:
age_unvacc_mean = df["Age-Adjusted Unvaccinated Rate"].mean()
df["Age-Adjusted Unvaccinated Rate"] = df["Age-Adjusted Unvaccinated Rate"].fillna(age_unvacc_mean)
df

,Outcome,Week End,Age Group,Unvaccinated Rate,Vaccinated Rate,Boosted Rate,Crude Vaccinated Ratio,Crude Boosted Ratio,Age-Adjusted Unvaccinated Rate,Age-Adjusted Vaccinated Rate,...,Age-Adjusted Vaccinated Ratio,Age-Adjusted Boosted Ratio,Population Unvaccinated,Population Vaccinated,Population Boosted,Outcome Unvaccinated,Outcome Vaccinated,Outcome Boosted,Age Group Min,Age Group Max
0,Deaths,10/01/2022,All,0.3,0.100000,0.900000,3.00000,0.3000,0.400000,0.3,...,1.3,0.7,591822,842535.0,1037067.0,2,1.0,9.0,999,999
1,Deaths,07/09/2022,0-4,0.0,42.439521,48.649783,4.54694,2.9523,80.741487,NaN,...,NaN,NaN,162642,NaN,NaN,0,NaN,NaN,0,4
2,Cases,11/12/2022,0-4,82.4,5.500000,48.649783,15.00000,2.9523,80.741487,NaN,...,NaN,NaN,162642,NaN,NaN,134,9.0,NaN,0,4
3,Hospitalizations,08/13/2022,0-4,7.4,0.000000,48.649783,4.54694,2.9523,80.741487,NaN,...,NaN,NaN,162642,NaN,NaN,12,0.0,NaN,0,4
4,Cases,02/26/2022,0-4,54.1,42.439521,48.649783,4.54694,2.9523,80.741487,NaN,...,NaN,NaN,162642,NaN,NaN,88,NaN,NaN,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Deaths,11/13/2021,65-79,8.7,5.500000,1.800000,1.60000,4.8000,80.741487,NaN,...,NaN,NaN,57295,146087.0,56482.0,5,8.0,1.0,65,79
3749,Cases,09/30/2023,18-29,51.0,17.700000,19.800000,2.90000,2.6000,80.741487,NaN,...,NaN,NaN,72503,214130.0,161728.0,37,38.0,32.0,18,29
3750,Deaths,10/09/2021,80+,16.4,3.800000,48.649783,4.30000,2.9523,80.741487,NaN,...,NaN,NaN,30481,52266.0,NaN,5,2.0,NaN,80,200
3751,Deaths,09/25/2021,80+,19.4,1.900000,48.649783,10.20000,2.9523,80.741487,NaN,...,NaN,NaN,30936,52848.0,NaN,6,1.0,NaN,80,200
3752,Cases,10/16/2021,80+,33.0,40.000000,48.649783,0.80000,2.9523,80.741487,NaN,...,NaN,NaN,30320,49996.0,NaN,10,20.0,NaN,80,200

In [20]:
age_vacc_mean = df["Age-Adjusted Vaccinated Rate"].mean()
df["Age-Adjusted Vaccinated Rate"] = df["Age-Adjusted Vaccinated Rate"].fillna(age_vacc_mean)
df

,Outcome,Week End,Age Group,Unvaccinated Rate,Vaccinated Rate,Boosted Rate,Crude Vaccinated Ratio,Crude Boosted Ratio,Age-Adjusted Unvaccinated Rate,Age-Adjusted Vaccinated Rate,...,Age-Adjusted Vaccinated Ratio,Age-Adjusted Boosted Ratio,Population Unvaccinated,Population Vaccinated,Population Boosted,Outcome Unvaccinated,Outcome Vaccinated,Outcome Boosted,Age Group Min,Age Group Max
0,Deaths,10/01/2022,All,0.3,0.100000,0.900000,3.00000,0.3000,0.400000,0.300000,...,1.3,0.7,591822,842535.0,1037067.0,2,1.0,9.0,999,999
1,Deaths,07/09/2022,0-4,0.0,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,NaN,NaN,162642,NaN,NaN,0,NaN,NaN,0,4
2,Cases,11/12/2022,0-4,82.4,5.500000,48.649783,15.00000,2.9523,80.741487,37.654916,...,NaN,NaN,162642,NaN,NaN,134,9.0,NaN,0,4
3,Hospitalizations,08/13/2022,0-4,7.4,0.000000,48.649783,4.54694,2.9523,80.741487,37.654916,...,NaN,NaN,162642,NaN,NaN,12,0.0,NaN,0,4
4,Cases,02/26/2022,0-4,54.1,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,NaN,NaN,162642,NaN,NaN,88,NaN,NaN,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Deaths,11/13/2021,65-79,8.7,5.500000,1.800000,1.60000,4.8000,80.741487,37.654916,...,NaN,NaN,57295,146087.0,56482.0,5,8.0,1.0,65,79
3749,Cases,09/30/2023,18-29,51.0,17.700000,19.800000,2.90000,2.6000,80.741487,37.654916,...,NaN,NaN,72503,214130.0,161728.0,37,38.0,32.0,18,29
3750,Deaths,10/09/2021,80+,16.4,3.800000,48.649783,4.30000,2.9523,80.741487,37.654916,...,NaN,NaN,30481,52266.0,NaN,5,2.0,NaN,80,200
3751,Deaths,09/25/2021,80+,19.4,1.900000,48.649783,10.20000,2.9523,80.741487,37.654916,...,NaN,NaN,30936,52848.0,NaN,6,1.0,NaN,80,200
3752,Cases,10/16/2021,80+,33.0,40.000000,48.649783,0.80000,2.9523,80.741487,37.654916,...,NaN,NaN,30320,49996.0,NaN,10,20.0,NaN,80,200

In [22]:
age_vaccratio_mean = df["Age-Adjusted Vaccinated Ratio"].mean()
df["Age-Adjusted Vaccinated Ratio"] = df["Age-Adjusted Vaccinated Ratio"].fillna(age_vaccratio_mean)
df

,Outcome,Week End,Age Group,Unvaccinated Rate,Vaccinated Rate,Boosted Rate,Crude Vaccinated Ratio,Crude Boosted Ratio,Age-Adjusted Unvaccinated Rate,Age-Adjusted Vaccinated Rate,...,Age-Adjusted Vaccinated Ratio,Age-Adjusted Boosted Ratio,Population Unvaccinated,Population Vaccinated,Population Boosted,Outcome Unvaccinated,Outcome Vaccinated,Outcome Boosted,Age Group Min,Age Group Max
0,Deaths,10/01/2022,All,0.3,0.100000,0.900000,3.00000,0.3000,0.400000,0.300000,...,1.300000,0.7,591822,842535.0,1037067.0,2,1.0,9.0,999,999
1,Deaths,07/09/2022,0-4,0.0,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,NaN,162642,NaN,NaN,0,NaN,NaN,0,4
2,Cases,11/12/2022,0-4,82.4,5.500000,48.649783,15.00000,2.9523,80.741487,37.654916,...,4.712368,NaN,162642,NaN,NaN,134,9.0,NaN,0,4
3,Hospitalizations,08/13/2022,0-4,7.4,0.000000,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,NaN,162642,NaN,NaN,12,0.0,NaN,0,4
4,Cases,02/26/2022,0-4,54.1,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,NaN,162642,NaN,NaN,88,NaN,NaN,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Deaths,11/13/2021,65-79,8.7,5.500000,1.800000,1.60000,4.8000,80.741487,37.654916,...,4.712368,NaN,57295,146087.0,56482.0,5,8.0,1.0,65,79
3749,Cases,09/30/2023,18-29,51.0,17.700000,19.800000,2.90000,2.6000,80.741487,37.654916,...,4.712368,NaN,72503,214130.0,161728.0,37,38.0,32.0,18,29
3750,Deaths,10/09/2021,80+,16.4,3.800000,48.649783,4.30000,2.9523,80.741487,37.654916,...,4.712368,NaN,30481,52266.0,NaN,5,2.0,NaN,80,200
3751,Deaths,09/25/2021,80+,19.4,1.900000,48.649783,10.20000,2.9523,80.741487,37.654916,...,4.712368,NaN,30936,52848.0,NaN,6,1.0,NaN,80,200
3752,Cases,10/16/2021,80+,33.0,40.000000,48.649783,0.80000,2.9523,80.741487,37.654916,...,4.712368,NaN,30320,49996.0,NaN,10,20.0,NaN,80,200

In [23]:
age_boost_mean = df["Age-Adjusted Boosted Ratio"].mean()
df["Age-Adjusted Boosted Ratio"] = df["Age-Adjusted Boosted Ratio"].fillna(age_boost_mean)
df

,Outcome,Week End,Age Group,Unvaccinated Rate,Vaccinated Rate,Boosted Rate,Crude Vaccinated Ratio,Crude Boosted Ratio,Age-Adjusted Unvaccinated Rate,Age-Adjusted Vaccinated Rate,...,Age-Adjusted Vaccinated Ratio,Age-Adjusted Boosted Ratio,Population Unvaccinated,Population Vaccinated,Population Boosted,Outcome Unvaccinated,Outcome Vaccinated,Outcome Boosted,Age Group Min,Age Group Max
0,Deaths,10/01/2022,All,0.3,0.100000,0.900000,3.00000,0.3000,0.400000,0.300000,...,1.300000,0.700000,591822,842535.0,1037067.0,2,1.0,9.0,999,999
1,Deaths,07/09/2022,0-4,0.0,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,NaN,NaN,0,NaN,NaN,0,4
2,Cases,11/12/2022,0-4,82.4,5.500000,48.649783,15.00000,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,NaN,NaN,134,9.0,NaN,0,4
3,Hospitalizations,08/13/2022,0-4,7.4,0.000000,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,NaN,NaN,12,0.0,NaN,0,4
4,Cases,02/26/2022,0-4,54.1,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,NaN,NaN,88,NaN,NaN,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Deaths,11/13/2021,65-79,8.7,5.500000,1.800000,1.60000,4.8000,80.741487,37.654916,...,4.712368,4.069551,57295,146087.0,56482.0,5,8.0,1.0,65,79
3749,Cases,09/30/2023,18-29,51.0,17.700000,19.800000,2.90000,2.6000,80.741487,37.654916,...,4.712368,4.069551,72503,214130.0,161728.0,37,38.0,32.0,18,29
3750,Deaths,10/09/2021,80+,16.4,3.800000,48.649783,4.30000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30481,52266.0,NaN,5,2.0,NaN,80,200
3751,Deaths,09/25/2021,80+,19.4,1.900000,48.649783,10.20000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30936,52848.0,NaN,6,1.0,NaN,80,200
3752,Cases,10/16/2021,80+,33.0,40.000000,48.649783,0.80000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30320,49996.0,NaN,10,20.0,NaN,80,200

In [24]:
pop_vacc_mean = df["Population Vaccinated"].mean()
df["Population Vaccinated"] = df["Population Vaccinated"].fillna(pop_vacc_mean)
df

,Outcome,Week End,Age Group,Unvaccinated Rate,Vaccinated Rate,Boosted Rate,Crude Vaccinated Ratio,Crude Boosted Ratio,Age-Adjusted Unvaccinated Rate,Age-Adjusted Vaccinated Rate,...,Age-Adjusted Vaccinated Ratio,Age-Adjusted Boosted Ratio,Population Unvaccinated,Population Vaccinated,Population Boosted,Outcome Unvaccinated,Outcome Vaccinated,Outcome Boosted,Age Group Min,Age Group Max
0,Deaths,10/01/2022,All,0.3,0.100000,0.900000,3.00000,0.3000,0.400000,0.300000,...,1.300000,0.700000,591822,842535.000000,1037067.0,2,1.0,9.0,999,999
1,Deaths,07/09/2022,0-4,0.0,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,NaN,0,NaN,NaN,0,4
2,Cases,11/12/2022,0-4,82.4,5.500000,48.649783,15.00000,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,NaN,134,9.0,NaN,0,4
3,Hospitalizations,08/13/2022,0-4,7.4,0.000000,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,NaN,12,0.0,NaN,0,4
4,Cases,02/26/2022,0-4,54.1,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,NaN,88,NaN,NaN,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Deaths,11/13/2021,65-79,8.7,5.500000,1.800000,1.60000,4.8000,80.741487,37.654916,...,4.712368,4.069551,57295,146087.000000,56482.0,5,8.0,1.0,65,79
3749,Cases,09/30/2023,18-29,51.0,17.700000,19.800000,2.90000,2.6000,80.741487,37.654916,...,4.712368,4.069551,72503,214130.000000,161728.0,37,38.0,32.0,18,29
3750,Deaths,10/09/2021,80+,16.4,3.800000,48.649783,4.30000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30481,52266.000000,NaN,5,2.0,NaN,80,200
3751,Deaths,09/25/2021,80+,19.4,1.900000,48.649783,10.20000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30936,52848.000000,NaN,6,1.0,NaN,80,200
3752,Cases,10/16/2021,80+,33.0,40.000000,48.649783,0.80000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30320,49996.000000,NaN,10,20.0,NaN,80,200

In [25]:
pop_boost_mean = df["Population Boosted"].mean()
df["Population Boosted"] = df["Population Boosted"].fillna(pop_boost_mean)
df

,Outcome,Week End,Age Group,Unvaccinated Rate,Vaccinated Rate,Boosted Rate,Crude Vaccinated Ratio,Crude Boosted Ratio,Age-Adjusted Unvaccinated Rate,Age-Adjusted Vaccinated Rate,...,Age-Adjusted Vaccinated Ratio,Age-Adjusted Boosted Ratio,Population Unvaccinated,Population Vaccinated,Population Boosted,Outcome Unvaccinated,Outcome Vaccinated,Outcome Boosted,Age Group Min,Age Group Max
0,Deaths,10/01/2022,All,0.3,0.100000,0.900000,3.00000,0.3000,0.400000,0.300000,...,1.300000,0.700000,591822,842535.000000,1.037067e+06,2,1.0,9.0,999,999
1,Deaths,07/09/2022,0-4,0.0,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,2.427838e+05,0,NaN,NaN,0,4
2,Cases,11/12/2022,0-4,82.4,5.500000,48.649783,15.00000,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,2.427838e+05,134,9.0,NaN,0,4
3,Hospitalizations,08/13/2022,0-4,7.4,0.000000,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,2.427838e+05,12,0.0,NaN,0,4
4,Cases,02/26/2022,0-4,54.1,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,2.427838e+05,88,NaN,NaN,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Deaths,11/13/2021,65-79,8.7,5.500000,1.800000,1.60000,4.8000,80.741487,37.654916,...,4.712368,4.069551,57295,146087.000000,5.648200e+04,5,8.0,1.0,65,79
3749,Cases,09/30/2023,18-29,51.0,17.700000,19.800000,2.90000,2.6000,80.741487,37.654916,...,4.712368,4.069551,72503,214130.000000,1.617280e+05,37,38.0,32.0,18,29
3750,Deaths,10/09/2021,80+,16.4,3.800000,48.649783,4.30000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30481,52266.000000,2.427838e+05,5,2.0,NaN,80,200
3751,Deaths,09/25/2021,80+,19.4,1.900000,48.649783,10.20000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30936,52848.000000,2.427838e+05,6,1.0,NaN,80,200
3752,Cases,10/16/2021,80+,33.0,40.000000,48.649783,0.80000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30320,49996.000000,2.427838e+05,10,20.0,NaN,80,200

In [26]:
out_vacc_mean = df["Outcome Vaccinated"].mean()
df["Outcome Vaccinated"] = df["Outcome Vaccinated"].fillna(out_vacc_mean)
df

,Outcome,Week End,Age Group,Unvaccinated Rate,Vaccinated Rate,Boosted Rate,Crude Vaccinated Ratio,Crude Boosted Ratio,Age-Adjusted Unvaccinated Rate,Age-Adjusted Vaccinated Rate,...,Age-Adjusted Vaccinated Ratio,Age-Adjusted Boosted Ratio,Population Unvaccinated,Population Vaccinated,Population Boosted,Outcome Unvaccinated,Outcome Vaccinated,Outcome Boosted,Age Group Min,Age Group Max
0,Deaths,10/01/2022,All,0.3,0.100000,0.900000,3.00000,0.3000,0.400000,0.300000,...,1.300000,0.700000,591822,842535.000000,1.037067e+06,2,1.000000,9.0,999,999
1,Deaths,07/09/2022,0-4,0.0,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,2.427838e+05,0,98.722125,NaN,0,4
2,Cases,11/12/2022,0-4,82.4,5.500000,48.649783,15.00000,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,2.427838e+05,134,9.000000,NaN,0,4
3,Hospitalizations,08/13/2022,0-4,7.4,0.000000,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,2.427838e+05,12,0.000000,NaN,0,4
4,Cases,02/26/2022,0-4,54.1,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,2.427838e+05,88,98.722125,NaN,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Deaths,11/13/2021,65-79,8.7,5.500000,1.800000,1.60000,4.8000,80.741487,37.654916,...,4.712368,4.069551,57295,146087.000000,5.648200e+04,5,8.000000,1.0,65,79
3749,Cases,09/30/2023,18-29,51.0,17.700000,19.800000,2.90000,2.6000,80.741487,37.654916,...,4.712368,4.069551,72503,214130.000000,1.617280e+05,37,38.000000,32.0,18,29
3750,Deaths,10/09/2021,80+,16.4,3.800000,48.649783,4.30000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30481,52266.000000,2.427838e+05,5,2.000000,NaN,80,200
3751,Deaths,09/25/2021,80+,19.4,1.900000,48.649783,10.20000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30936,52848.000000,2.427838e+05,6,1.000000,NaN,80,200
3752,Cases,10/16/2021,80+,33.0,40.000000,48.649783,0.80000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30320,49996.000000,2.427838e+05,10,20.000000,NaN,80,200

In [27]:
out_boost_mean = df["Outcome Boosted"].mean()
df["Outcome Boosted"] = df["Outcome Boosted"].fillna(out_boost_mean)
df

,Outcome,Week End,Age Group,Unvaccinated Rate,Vaccinated Rate,Boosted Rate,Crude Vaccinated Ratio,Crude Boosted Ratio,Age-Adjusted Unvaccinated Rate,Age-Adjusted Vaccinated Rate,...,Age-Adjusted Vaccinated Ratio,Age-Adjusted Boosted Ratio,Population Unvaccinated,Population Vaccinated,Population Boosted,Outcome Unvaccinated,Outcome Vaccinated,Outcome Boosted,Age Group Min,Age Group Max
0,Deaths,10/01/2022,All,0.3,0.100000,0.900000,3.00000,0.3000,0.400000,0.300000,...,1.300000,0.700000,591822,842535.000000,1.037067e+06,2,1.000000,9.000000,999,999
1,Deaths,07/09/2022,0-4,0.0,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,2.427838e+05,0,98.722125,112.262554,0,4
2,Cases,11/12/2022,0-4,82.4,5.500000,48.649783,15.00000,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,2.427838e+05,134,9.000000,112.262554,0,4
3,Hospitalizations,08/13/2022,0-4,7.4,0.000000,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,2.427838e+05,12,0.000000,112.262554,0,4
4,Cases,02/26/2022,0-4,54.1,42.439521,48.649783,4.54694,2.9523,80.741487,37.654916,...,4.712368,4.069551,162642,251186.798008,2.427838e+05,88,98.722125,112.262554,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Deaths,11/13/2021,65-79,8.7,5.500000,1.800000,1.60000,4.8000,80.741487,37.654916,...,4.712368,4.069551,57295,146087.000000,5.648200e+04,5,8.000000,1.000000,65,79
3749,Cases,09/30/2023,18-29,51.0,17.700000,19.800000,2.90000,2.6000,80.741487,37.654916,...,4.712368,4.069551,72503,214130.000000,1.617280e+05,37,38.000000,32.000000,18,29
3750,Deaths,10/09/2021,80+,16.4,3.800000,48.649783,4.30000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30481,52266.000000,2.427838e+05,5,2.000000,112.262554,80,200
3751,Deaths,09/25/2021,80+,19.4,1.900000,48.649783,10.20000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30936,52848.000000,2.427838e+05,6,1.000000,112.262554,80,200
3752,Cases,10/16/2021,80+,33.0,40.000000,48.649783,0.80000,2.9523,80.741487,37.654916,...,4.712368,4.069551,30320,49996.000000,2.427838e+05,10,20.000000,112.262554,80,200